from datetime import date, datetime
from typing import Optional

from pydantic import BaseModel


class FichaInscripcionModel(BaseModel):
    id : Optional[int] = None
    id_sede : Optional[int] = None
    nom_sede: Optional[str] = None
    fecha: Optional[date] = None
    tipo_contrato: Optional[str] = None
    servicio: Optional[str] = None
    num_contrato: Optional[str] = None
    tipo_persona: Optional[str] = None
    tipo_documento: Optional[str] = None
    num_documento : Optional[int] = None
    nombres: Optional[str] = None
    categoria: Optional[str] = None
    zona: Optional[str] = None
    distrito: Optional[str] = None
    telefono: Optional[str] = None
    celulares: Optional[str] = None
    correo: Optional[str] = None
    estado_ficha: Optional[str] = None
    canal_atencion: Optional[str] = None
    vendedor: Optional[str] = None
    fecha_ingreso: Optional[datetime] = None
    nombre_aprobador: Optional[str] = None
    fecha_aprobación: Optional[datetime] = None
    obs_servicio: Optional[str] = None
    obs_vendedor: Optional[str] = None
    mot_desaprobacion: Optional[str] = None
    codigo_abonado : Optional[int] = None
    fecha_inst_catv : Optional[date] = None
    horai_ejec_cable : Optional[str] = None
    horaf_ejec_cable : Optional[str] = None
    fecha_inst_int : Optional[date] = None
    horai_ejec_int : Optional[str] = None
    horaf_ejec_int : Optional[str] = None
    id_ficha : Optional[int] = None
    usuario_ingreso : Optional[str] = None
    paq_inicial : Optional[str] = None
    fecha_insert : Optional[datetime] = None
    fecha_update : Optional[datetime] = None
    class Config:
        orm_mode = True

class OrdenServicio(BaseModel):
    id : Optional[int] = None
    id_sede : Optional[int] = None
    nom_sede : Optional[str] = None
    id_os : Optional[int] = None
    tipo_os : Optional[str] = None
    detalle_os : Optional[str] = None
    cod_servicio : Optional[str] = None
    servicio : Optional[str] = None
    estado_cable : Optional[str] = None
    estado_internet : Optional[str] = None
    estado_tvdigital : Optional[str] = None
    tarifa_act_cable : Optional[str] = None
    tarifa_act_internet : Optional[str] = None
    tarifa_act_tvdigital : Optional[str] = None
    precio_servicio : Optional[float] = None
    precio_os : Optional[float] = None
    ptos_princ_install : Optional[int] = None
    ptos_add_install : Optional[int] = None
    abonado : Optional[int] = None
    nro_os : Optional[str] = None
    zona : Optional[str] = None
    nom_abonado : Optional[str] = None
    distrito : Optional[str] = None
    sector : Optional[str] = None
    ruta : Optional[str] = None
    nro_casa : Optional[str] = None
    edificio : Optional[str] = None
    torre : Optional[str] = None
    ref_direccion : Optional[str] = None
    longitud : Optional[str] = None
    latitud : Optional[str] = None
    total_deuda : Optional[float] = None
    cant_meses_deuda : Optional[int] = None
    fecha_recep : Optional[date] = None
    fecha_ejecucion : Optional[date] = None
    fecha_install : Optional[date] = None
    hora : Optional[str] = None
    fecha_atencion : Optional[date] = None
    hora_inicial : Optional[str] = None
    hora_final : Optional[str] = None
    estado_os : Optional[str] = None
    tec_ejecutor : Optional[str] = None
    vendedor : Optional[str] = None
    observaciones : Optional[str] = None
    plano1 : Optional[str] = None
    dispositivo : Optional[str] = None
    telefono : Optional[str] = None
    celulares : Optional[str] = None
    tec_responsable : Optional[str] = None
    obs_tecnico : Optional[str] = None
    detalle_material : Optional[str] = None
    tap : Optional[str] = None
    caja : Optional[str] = None
    poste : Optional[str] = None
    dias_espera : Optional[int] = None
    lugar_averia : Optional[str] = None
    causa : Optional[str] = None
    sub_causa : Optional[str] = None
    solucion : Optional[str] = None
    cant_visitas_tec : Optional[int] = None
    usuario_ing : Optional[str] = None
    fecha_ingreso : Optional[datetime] = None
    usuario_mod : Optional[str] = None
    fecha_mod : Optional[datetime] = None
    nro_anexo_princ : Optional[float] = None
    nro_anexo_add : Optional[float] = None
    mot_anulacion : Optional[str] = None
    nom_emp_ult_mod : Optional[str] = None
    fecha_ult_corte : Optional[date] = None
    fecha_inscripcion : Optional[date] = None
    por_reprogramar : Optional[str] = None
    tecnologia : Optional[str] = None
    forma_aviso : Optional[str] = None
    hora_creacion_ficha : Optional[str] = None
    catv_plan_inicial : Optional[str] = None
    catv_precio_plan_inicial : Optional[float] = None
    catv_fecha_plan_inicial : Optional[date] = None
    catv_segundo_plan : Optional[str] = None
    catv_precio_plan_segundo : Optional[float] = None
    catv_fecha_plan_segundo : Optional[date] = None
    catv_tercer_plan : Optional[str] = None
    catv_precio_plan_tercero : Optional[float] = None
    catv_fecha_plan_tercero : Optional[date] = None
    int_plan_inicial : Optional[str] = None
    int_precio_plan_inicial : Optional[float] = None
    int_fecha_plan_inicial : Optional[date] = None
    int_segundo_plan : Optional[str] = None
    int_precio_plan_segundo : Optional[float] = None
    int_fecha_plan_segundo : Optional[date] = None
    int_tercer_plan : Optional[str] = None
    int_precio_plan_tercero : Optional[float] = None
    int_fecha_plan_tercero : Optional[date] = None
    fecha_insert : Optional[datetime] = None
    fecha_update : Optional[datetime] = None
    class Config:
        orm_mode = True